version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ./config:/config
    ports:
      - 8081:80
      - 4434:443
    restart: unless-stopped