version: '3.4'

services:
  apilaserfichefolderagent:
    image: apilaserfichefolderagent
    restart: unless-stopped
    deploy:
      replicas: 3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - VERSION=${VERSION}
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
    - /mnt/DocsPQR:/mnt/DocsPQR
  nginx:
    image: nginx:1.21.6
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/ssl
    depends_on:
      - apilaserfichefolderagent
    ports:
      - "5004:443"