version: "3.3"
services:
  teamcity-server:
    container_name: teamcity-server-instance
    volumes:
      - "./datadir/:/data/teamcity_server/datadir"
      - "./logs/:/opt/teamcity/logs"
    ports:
      - "8111:8111"
    image: jetbrains/teamcity-server
    networks:
      internal_network:
        ipv4_address: 172.20.1.2

  # se necesita dos agentes puedes correrlo en local
  # Debes correr en el host este comando para que el agente pueda correr docker =>>  chmod 666 /var/run/docker.sock
  teamcity-agent:
    environment:
      - "SERVER_URL=http://172.20.1.2:8111/"
      - "DOCKER_IN_DOCKER=start"
    volumes:
      - "teamcity_agent_conf:/data/teamcity_agent/conf"
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: jetbrains/teamcity-agent
    networks:
      - internal_network
      
volumes:
    teamcity_agent_conf:

networks:
    internal_network:
       ipam:
          driver: default
          config:
             - subnet: "172.20.1.0/24"
