version: "3.3"

services:
  traefik:
    image: "traefik:v2.1"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: nginx
    labels:
      - traefik.http.routers.nginx.rule=Host(`local.ng.com`)
