version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 81:80/tcp
      - 445:443/tcp
      - 853:853/tcp
      - 3100:3000/tcp
    volumes:
      - /home/ubuntu/adguard/work:/opt/adguardhome/work
      - /home/ubuntu/adguard/config:/opt/adguardhome/conf
    restart: unless-stopped
